#!/bin/bash

setup-cluster:
    echo "Bringing the HA cluster of k8s....!" 
    ansible-playbook -b -v -i inventory/sample/inventory.ini cluster.yml
destroy-cluster:
    echo "Reset the whole cluster of k8s....!"
    ansible-playbook -b -v -i inventory/sample/inventory.ini reset.yml