[all:vars]
ansible_user=macos
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[kube_control_plane]
node1 ansible_host=34.50.71.235ansible_connection=local # ip=10.3.0.1 etcd_member_name=etcd1
node2 ansible_host=34.101.104.157 # ip=10.3.0.2 etcd_member_name=etcd2
node3 ansible_host=34.101.223.233 # ip=10.3.0.3 etcd_member_name=etcd3

[etcd:children]
kube_control_plane

[kube_node]
node4 ansible_host=34.150.10.27 # ip=10.3.0.4
node5 ansible_host=34.96.224.252 # ip=10.3.0.5
# node6 ansible_host=95.54.0.17  # ip=10.3.0.6
